In [1]:
print("Let's Go Machine Learning")

Let's Go Machine Learning

In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [3]:
#-----Load the data  to a DataFrame
df = pd.read_csv("../data/students.csv")
df

     Name  Math  Physics  Chemistry
0   Ahmed    80       75         90
1    Sara    95       88         91
2    John    70       60         75
3  Fatima    88       92         85
4     Ali    65       70         60
5   Yusuf    90       89         93
6  Meryem    78       82         80
7    Adam    85       79         88

In [8]:
print(df.head() )   #------------5 FIRST ROWS
print(df.tail()  )  #---------5 last rows
df.info()          #------Info about the dataframe
df.describe()      #--------Statistics

     Name  Math  Physics  Chemistry
0   Ahmed    80       75         90
1    Sara    95       88         91
2    John    70       60         75
3  Fatima    88       92         85
4     Ali    65       70         60
     Name  Math  Physics  Chemistry
3  Fatima    88       92         85
4     Ali    65       70         60
5   Yusuf    90       89         93
6  Meryem    78       82         80
7    Adam    85       79         88
<class 'pandas.DataFrame'>
RangeIndex: 8 entries, 0 to 7
Data columns (total 4 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Name       8 non-null      str
 1   Math       8 non-null      int64
 2   Physics    8 non-null      int64
 3   Chemistry  8 non-null      int64
dtypes: int64(3), str(1)
memory usage: 388.0 bytes

            Math    Physics  Chemistry
count   8.000000   8.000000   8.000000
mean   81.375000  79.375000  82.750000
std    10.197163  10.795998  10.977249
min    65.000000  60.000000  60.000000
25%    76.000000  73.750000  78.750000
50%    82.500000  80.500000  86.500000
75%    88.500000  88.250000  90.250000
max    95.000000  92.000000  93.000000

In [17]:
print(df['Math'])
print(df.loc[[0,1]])

0    80
1    95
2    70
3    88
4    65
5    90
6    78
7    85
Name: Math, dtype: int64
    Name  Math  Physics  Chemistry
0  Ahmed    80       75         90
1   Sara    95       88         91

In [6]:
df.isnull()           #---Check for missing value
df.isnull().sum()   #---count the missing values

Name         0
Math         0
Physics      0
Chemistry    0
dtype: int64

In [5]:
#Create a new column  Average
df['Average'] = (df["Math"] +df["Physics"] + df["Chemistry"])/3

In [6]:
df['Average']= df['Average'].round(2)
df
print(df.loc[df['Average'].idxmax()]) #Find the student with the highest average
print(df.loc[df['Average'].idxmin()]) #Find the student with the lowest average
print(df.sort_values(by='Average',ascending=True))
print(df[['Name','Average']])

df.to_csv("../reports/students_with_average.csv",index=False) #Create a new dataset

Name          Sara
Math            95
Physics         88
Chemistry       91
Average      91.33
Name: 1, dtype: object
Name          Ali
Math           65
Physics        70
Chemistry      60
Average      65.0
Name: 4, dtype: object
     Name  Math  Physics  Chemistry  Average
4     Ali    65       70         60    65.00
2    John    70       60         75    68.33
6  Meryem    78       82         80    80.00
0   Ahmed    80       75         90    81.67
7    Adam    85       79         88    84.00
3  Fatima    88       92         85    88.33
5   Yusuf    90       89         93    90.67
1    Sara    95       88         91    91.33
     Name  Average
0   Ahmed    81.67
1    Sara    91.33
2    John    68.33
3  Fatima    88.33
4     Ali    65.00
5   Yusuf    90.67
6  Meryem    80.00
7    Adam    84.00

In [13]:
#1 get students whose average is greater than 85?
gr85 = df['Average'] > 85
print(df[gr85])

#2 get only students whose Physics score is greater than 80?
ph80 = df['Physics'] > 80
print(df[ph80])

#3 get students whose Math score is less than 75?
mat75 = df['Math'] < 75
print(df[mat75])

     Name  Math  Physics  Chemistry  Average
1    Sara    95       88         91    91.33
3  Fatima    88       92         85    88.33
5   Yusuf    90       89         93    90.67
     Name  Math  Physics  Chemistry  Average
1    Sara    95       88         91    91.33
3  Fatima    88       92         85    88.33
5   Yusuf    90       89         93    90.67
6  Meryem    78       82         80    80.00
   Name  Math  Physics  Chemistry  Average
2  John    70       60         75    68.33
4   Ali    65       70         60    65.00